export const PARTICIPANTS = [
  { id: 1, name: "우경준", team: "동서울인프라팀" },
  { id: 2, name: "김기성", team: "동서울인프라팀" },
  { id: 3, name: "가현", team: "동서울인프라팀" },
  { id: 4, name: "정찬호", team: "동서울인프라팀" },
  { id: 5, name: "김준환", team: "동서울인프라팀" },
  { id: 6, name: "윤동현", team: "동서울인프라팀" },
  { id: 7, name: "조수영", team: "동서울인프라팀" },
  { id: 8, name: "나상훈", team: "동서울인프라팀" },
  { id: 9, name: "김전수", team: "동서울인프라팀" },
  { id: 10, name: "곽동준", team: "동서울인프라팀" },
  { id: 11, name: "조남훈", team: "동서울인프라팀" },
  { id: 12, name: "이민재", team: "동서울인프라팀" },
  { id: 13, name: "김규민", team: "동서울인프라팀" },
  { id: 14, name: "고명균", team: "동서울인프라팀" },
  { id: 15, name: "홍임석", team: "동서울인프라팀" },
  { id: 16, name: "차진석", team: "동서울인프라팀" },
  { id: 17, name: "김기돈", team: "동서울인프라팀" },
  { id: 18, name: "인영환", team: "동서울인프라팀" },
] as const